apiVersion: v1
kind: Service
metadata:
  name: classicbusinessmodel-service
spec:
  selector:
    app: classicbusinessmodel-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer