apiVersion: apps/v1
kind: Deployment
metadata:
  name: classicbusinessmodel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classicbusinessmodel
  template:
    metadata:
      labels:
        app: classicbusinessmodel
    spec:
      containers:
        - name: classicbusinessmodel
          image: viddeshpowarcap/sprint-springboot
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://kopdbvid.cmdlxfdnrfju.ap-south-1.rds.amazonaws.com:3306/classicmodels
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
